// Code generated by MockGen. DO NOT EDIT.
// Source: k8s.io/client-go/kubernetes/typed/core/v1 (interfaces: ServiceAccountInterface)
//
// Generated by this command:
//
//	mockgen -typed -package mocks -destination mocks/serviceaccount_mock.go k8s.io/client-go/kubernetes/typed/core/v1 ServiceAccountInterface
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	v1 "k8s.io/api/authentication/v1"
	v10 "k8s.io/api/core/v1"
	v11 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	v12 "k8s.io/client-go/applyconfigurations/core/v1"
)

// MockServiceAccountInterface is a mock of ServiceAccountInterface interface.
type MockServiceAccountInterface struct {
	ctrl     *gomock.Controller
	recorder *MockServiceAccountInterfaceMockRecorder
	isgomock struct{}
}

// MockServiceAccountInterfaceMockRecorder is the mock recorder for MockServiceAccountInterface.
type MockServiceAccountInterfaceMockRecorder struct {
	mock *MockServiceAccountInterface
}

// NewMockServiceAccountInterface creates a new mock instance.
func NewMockServiceAccountInterface(ctrl *gomock.Controller) *MockServiceAccountInterface {
	mock := &MockServiceAccountInterface{ctrl: ctrl}
	mock.recorder = &MockServiceAccountInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServiceAccountInterface) EXPECT() *MockServiceAccountInterfaceMockRecorder {
	return m.recorder
}

// Apply mocks base method.
func (m *MockServiceAccountInterface) Apply(ctx context.Context, serviceAccount *v12.ServiceAccountApplyConfiguration, opts v11.ApplyOptions) (*v10.ServiceAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Apply", ctx, serviceAccount, opts)
	ret0, _ := ret[0].(*v10.ServiceAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Apply indicates an expected call of Apply.
func (mr *MockServiceAccountInterfaceMockRecorder) Apply(ctx, serviceAccount, opts any) *MockServiceAccountInterfaceApplyCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Apply", reflect.TypeOf((*MockServiceAccountInterface)(nil).Apply), ctx, serviceAccount, opts)
	return &MockServiceAccountInterfaceApplyCall{Call: call}
}

// MockServiceAccountInterfaceApplyCall wrap *gomock.Call
type MockServiceAccountInterfaceApplyCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceAccountInterfaceApplyCall) Return(result *v10.ServiceAccount, err error) *MockServiceAccountInterfaceApplyCall {
	c.Call = c.Call.Return(result, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceAccountInterfaceApplyCall) Do(f func(context.Context, *v12.ServiceAccountApplyConfiguration, v11.ApplyOptions) (*v10.ServiceAccount, error)) *MockServiceAccountInterfaceApplyCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceAccountInterfaceApplyCall) DoAndReturn(f func(context.Context, *v12.ServiceAccountApplyConfiguration, v11.ApplyOptions) (*v10.ServiceAccount, error)) *MockServiceAccountInterfaceApplyCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Create mocks base method.
func (m *MockServiceAccountInterface) Create(ctx context.Context, serviceAccount *v10.ServiceAccount, opts v11.CreateOptions) (*v10.ServiceAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, serviceAccount, opts)
	ret0, _ := ret[0].(*v10.ServiceAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockServiceAccountInterfaceMockRecorder) Create(ctx, serviceAccount, opts any) *MockServiceAccountInterfaceCreateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockServiceAccountInterface)(nil).Create), ctx, serviceAccount, opts)
	return &MockServiceAccountInterfaceCreateCall{Call: call}
}

// MockServiceAccountInterfaceCreateCall wrap *gomock.Call
type MockServiceAccountInterfaceCreateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceAccountInterfaceCreateCall) Return(arg0 *v10.ServiceAccount, arg1 error) *MockServiceAccountInterfaceCreateCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceAccountInterfaceCreateCall) Do(f func(context.Context, *v10.ServiceAccount, v11.CreateOptions) (*v10.ServiceAccount, error)) *MockServiceAccountInterfaceCreateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceAccountInterfaceCreateCall) DoAndReturn(f func(context.Context, *v10.ServiceAccount, v11.CreateOptions) (*v10.ServiceAccount, error)) *MockServiceAccountInterfaceCreateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CreateToken mocks base method.
func (m *MockServiceAccountInterface) CreateToken(ctx context.Context, serviceAccountName string, tokenRequest *v1.TokenRequest, opts v11.CreateOptions) (*v1.TokenRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateToken", ctx, serviceAccountName, tokenRequest, opts)
	ret0, _ := ret[0].(*v1.TokenRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateToken indicates an expected call of CreateToken.
func (mr *MockServiceAccountInterfaceMockRecorder) CreateToken(ctx, serviceAccountName, tokenRequest, opts any) *MockServiceAccountInterfaceCreateTokenCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateToken", reflect.TypeOf((*MockServiceAccountInterface)(nil).CreateToken), ctx, serviceAccountName, tokenRequest, opts)
	return &MockServiceAccountInterfaceCreateTokenCall{Call: call}
}

// MockServiceAccountInterfaceCreateTokenCall wrap *gomock.Call
type MockServiceAccountInterfaceCreateTokenCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceAccountInterfaceCreateTokenCall) Return(arg0 *v1.TokenRequest, arg1 error) *MockServiceAccountInterfaceCreateTokenCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceAccountInterfaceCreateTokenCall) Do(f func(context.Context, string, *v1.TokenRequest, v11.CreateOptions) (*v1.TokenRequest, error)) *MockServiceAccountInterfaceCreateTokenCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceAccountInterfaceCreateTokenCall) DoAndReturn(f func(context.Context, string, *v1.TokenRequest, v11.CreateOptions) (*v1.TokenRequest, error)) *MockServiceAccountInterfaceCreateTokenCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Delete mocks base method.
func (m *MockServiceAccountInterface) Delete(ctx context.Context, name string, opts v11.DeleteOptions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, name, opts)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockServiceAccountInterfaceMockRecorder) Delete(ctx, name, opts any) *MockServiceAccountInterfaceDeleteCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockServiceAccountInterface)(nil).Delete), ctx, name, opts)
	return &MockServiceAccountInterfaceDeleteCall{Call: call}
}

// MockServiceAccountInterfaceDeleteCall wrap *gomock.Call
type MockServiceAccountInterfaceDeleteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceAccountInterfaceDeleteCall) Return(arg0 error) *MockServiceAccountInterfaceDeleteCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceAccountInterfaceDeleteCall) Do(f func(context.Context, string, v11.DeleteOptions) error) *MockServiceAccountInterfaceDeleteCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceAccountInterfaceDeleteCall) DoAndReturn(f func(context.Context, string, v11.DeleteOptions) error) *MockServiceAccountInterfaceDeleteCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteCollection mocks base method.
func (m *MockServiceAccountInterface) DeleteCollection(ctx context.Context, opts v11.DeleteOptions, listOpts v11.ListOptions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCollection", ctx, opts, listOpts)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCollection indicates an expected call of DeleteCollection.
func (mr *MockServiceAccountInterfaceMockRecorder) DeleteCollection(ctx, opts, listOpts any) *MockServiceAccountInterfaceDeleteCollectionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCollection", reflect.TypeOf((*MockServiceAccountInterface)(nil).DeleteCollection), ctx, opts, listOpts)
	return &MockServiceAccountInterfaceDeleteCollectionCall{Call: call}
}

// MockServiceAccountInterfaceDeleteCollectionCall wrap *gomock.Call
type MockServiceAccountInterfaceDeleteCollectionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceAccountInterfaceDeleteCollectionCall) Return(arg0 error) *MockServiceAccountInterfaceDeleteCollectionCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceAccountInterfaceDeleteCollectionCall) Do(f func(context.Context, v11.DeleteOptions, v11.ListOptions) error) *MockServiceAccountInterfaceDeleteCollectionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceAccountInterfaceDeleteCollectionCall) DoAndReturn(f func(context.Context, v11.DeleteOptions, v11.ListOptions) error) *MockServiceAccountInterfaceDeleteCollectionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Get mocks base method.
func (m *MockServiceAccountInterface) Get(ctx context.Context, name string, opts v11.GetOptions) (*v10.ServiceAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, name, opts)
	ret0, _ := ret[0].(*v10.ServiceAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockServiceAccountInterfaceMockRecorder) Get(ctx, name, opts any) *MockServiceAccountInterfaceGetCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockServiceAccountInterface)(nil).Get), ctx, name, opts)
	return &MockServiceAccountInterfaceGetCall{Call: call}
}

// MockServiceAccountInterfaceGetCall wrap *gomock.Call
type MockServiceAccountInterfaceGetCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceAccountInterfaceGetCall) Return(arg0 *v10.ServiceAccount, arg1 error) *MockServiceAccountInterfaceGetCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceAccountInterfaceGetCall) Do(f func(context.Context, string, v11.GetOptions) (*v10.ServiceAccount, error)) *MockServiceAccountInterfaceGetCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceAccountInterfaceGetCall) DoAndReturn(f func(context.Context, string, v11.GetOptions) (*v10.ServiceAccount, error)) *MockServiceAccountInterfaceGetCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// List mocks base method.
func (m *MockServiceAccountInterface) List(ctx context.Context, opts v11.ListOptions) (*v10.ServiceAccountList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, opts)
	ret0, _ := ret[0].(*v10.ServiceAccountList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockServiceAccountInterfaceMockRecorder) List(ctx, opts any) *MockServiceAccountInterfaceListCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockServiceAccountInterface)(nil).List), ctx, opts)
	return &MockServiceAccountInterfaceListCall{Call: call}
}

// MockServiceAccountInterfaceListCall wrap *gomock.Call
type MockServiceAccountInterfaceListCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceAccountInterfaceListCall) Return(arg0 *v10.ServiceAccountList, arg1 error) *MockServiceAccountInterfaceListCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceAccountInterfaceListCall) Do(f func(context.Context, v11.ListOptions) (*v10.ServiceAccountList, error)) *MockServiceAccountInterfaceListCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceAccountInterfaceListCall) DoAndReturn(f func(context.Context, v11.ListOptions) (*v10.ServiceAccountList, error)) *MockServiceAccountInterfaceListCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Patch mocks base method.
func (m *MockServiceAccountInterface) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v11.PatchOptions, subresources ...string) (*v10.ServiceAccount, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, name, pt, data, opts}
	for _, a := range subresources {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Patch", varargs...)
	ret0, _ := ret[0].(*v10.ServiceAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Patch indicates an expected call of Patch.
func (mr *MockServiceAccountInterfaceMockRecorder) Patch(ctx, name, pt, data, opts any, subresources ...any) *MockServiceAccountInterfacePatchCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, name, pt, data, opts}, subresources...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Patch", reflect.TypeOf((*MockServiceAccountInterface)(nil).Patch), varargs...)
	return &MockServiceAccountInterfacePatchCall{Call: call}
}

// MockServiceAccountInterfacePatchCall wrap *gomock.Call
type MockServiceAccountInterfacePatchCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceAccountInterfacePatchCall) Return(result *v10.ServiceAccount, err error) *MockServiceAccountInterfacePatchCall {
	c.Call = c.Call.Return(result, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceAccountInterfacePatchCall) Do(f func(context.Context, string, types.PatchType, []byte, v11.PatchOptions, ...string) (*v10.ServiceAccount, error)) *MockServiceAccountInterfacePatchCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceAccountInterfacePatchCall) DoAndReturn(f func(context.Context, string, types.PatchType, []byte, v11.PatchOptions, ...string) (*v10.ServiceAccount, error)) *MockServiceAccountInterfacePatchCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Update mocks base method.
func (m *MockServiceAccountInterface) Update(ctx context.Context, serviceAccount *v10.ServiceAccount, opts v11.UpdateOptions) (*v10.ServiceAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, serviceAccount, opts)
	ret0, _ := ret[0].(*v10.ServiceAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockServiceAccountInterfaceMockRecorder) Update(ctx, serviceAccount, opts any) *MockServiceAccountInterfaceUpdateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockServiceAccountInterface)(nil).Update), ctx, serviceAccount, opts)
	return &MockServiceAccountInterfaceUpdateCall{Call: call}
}

// MockServiceAccountInterfaceUpdateCall wrap *gomock.Call
type MockServiceAccountInterfaceUpdateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceAccountInterfaceUpdateCall) Return(arg0 *v10.ServiceAccount, arg1 error) *MockServiceAccountInterfaceUpdateCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceAccountInterfaceUpdateCall) Do(f func(context.Context, *v10.ServiceAccount, v11.UpdateOptions) (*v10.ServiceAccount, error)) *MockServiceAccountInterfaceUpdateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceAccountInterfaceUpdateCall) DoAndReturn(f func(context.Context, *v10.ServiceAccount, v11.UpdateOptions) (*v10.ServiceAccount, error)) *MockServiceAccountInterfaceUpdateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Watch mocks base method.
func (m *MockServiceAccountInterface) Watch(ctx context.Context, opts v11.ListOptions) (watch.Interface, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Watch", ctx, opts)
	ret0, _ := ret[0].(watch.Interface)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Watch indicates an expected call of Watch.
func (mr *MockServiceAccountInterfaceMockRecorder) Watch(ctx, opts any) *MockServiceAccountInterfaceWatchCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Watch", reflect.TypeOf((*MockServiceAccountInterface)(nil).Watch), ctx, opts)
	return &MockServiceAccountInterfaceWatchCall{Call: call}
}

// MockServiceAccountInterfaceWatchCall wrap *gomock.Call
type MockServiceAccountInterfaceWatchCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceAccountInterfaceWatchCall) Return(arg0 watch.Interface, arg1 error) *MockServiceAccountInterfaceWatchCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceAccountInterfaceWatchCall) Do(f func(context.Context, v11.ListOptions) (watch.Interface, error)) *MockServiceAccountInterfaceWatchCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceAccountInterfaceWatchCall) DoAndReturn(f func(context.Context, v11.ListOptions) (watch.Interface, error)) *MockServiceAccountInterfaceWatchCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
