// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/juju/juju/apiserver/common/secrets (interfaces: SecretService,SecretBackendService)
//
// Generated by this command:
//
//	mockgen -typed -package mocks -destination mocks/commonsecrets_mock.go github.com/juju/juju/apiserver/common/secrets SecretService,SecretBackendService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/juju/juju/core/model"
	secrets "github.com/juju/juju/core/secrets"
	watcher "github.com/juju/juju/core/watcher"
	service "github.com/juju/juju/domain/secret/service"
	service0 "github.com/juju/juju/domain/secretbackend/service"
	gomock "go.uber.org/mock/gomock"
)

// MockSecretService is a mock of SecretService interface.
type MockSecretService struct {
	ctrl     *gomock.Controller
	recorder *MockSecretServiceMockRecorder
	isgomock struct{}
}

// MockSecretServiceMockRecorder is the mock recorder for MockSecretService.
type MockSecretServiceMockRecorder struct {
	mock *MockSecretService
}

// NewMockSecretService creates a new mock instance.
func NewMockSecretService(ctrl *gomock.Controller) *MockSecretService {
	mock := &MockSecretService{ctrl: ctrl}
	mock.recorder = &MockSecretServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSecretService) EXPECT() *MockSecretServiceMockRecorder {
	return m.recorder
}

// ChangeSecretBackend mocks base method.
func (m *MockSecretService) ChangeSecretBackend(ctx context.Context, uri *secrets.URI, revision int, params service.ChangeSecretBackendParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangeSecretBackend", ctx, uri, revision, params)
	ret0, _ := ret[0].(error)
	return ret0
}

// ChangeSecretBackend indicates an expected call of ChangeSecretBackend.
func (mr *MockSecretServiceMockRecorder) ChangeSecretBackend(ctx, uri, revision, params any) *MockSecretServiceChangeSecretBackendCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangeSecretBackend", reflect.TypeOf((*MockSecretService)(nil).ChangeSecretBackend), ctx, uri, revision, params)
	return &MockSecretServiceChangeSecretBackendCall{Call: call}
}

// MockSecretServiceChangeSecretBackendCall wrap *gomock.Call
type MockSecretServiceChangeSecretBackendCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSecretServiceChangeSecretBackendCall) Return(arg0 error) *MockSecretServiceChangeSecretBackendCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSecretServiceChangeSecretBackendCall) Do(f func(context.Context, *secrets.URI, int, service.ChangeSecretBackendParams) error) *MockSecretServiceChangeSecretBackendCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSecretServiceChangeSecretBackendCall) DoAndReturn(f func(context.Context, *secrets.URI, int, service.ChangeSecretBackendParams) error) *MockSecretServiceChangeSecretBackendCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListCharmSecretsToDrain mocks base method.
func (m *MockSecretService) ListCharmSecretsToDrain(ctx context.Context, owners ...service.CharmSecretOwner) ([]*secrets.SecretMetadataForDrain, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range owners {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListCharmSecretsToDrain", varargs...)
	ret0, _ := ret[0].([]*secrets.SecretMetadataForDrain)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCharmSecretsToDrain indicates an expected call of ListCharmSecretsToDrain.
func (mr *MockSecretServiceMockRecorder) ListCharmSecretsToDrain(ctx any, owners ...any) *MockSecretServiceListCharmSecretsToDrainCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, owners...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCharmSecretsToDrain", reflect.TypeOf((*MockSecretService)(nil).ListCharmSecretsToDrain), varargs...)
	return &MockSecretServiceListCharmSecretsToDrainCall{Call: call}
}

// MockSecretServiceListCharmSecretsToDrainCall wrap *gomock.Call
type MockSecretServiceListCharmSecretsToDrainCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSecretServiceListCharmSecretsToDrainCall) Return(arg0 []*secrets.SecretMetadataForDrain, arg1 error) *MockSecretServiceListCharmSecretsToDrainCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSecretServiceListCharmSecretsToDrainCall) Do(f func(context.Context, ...service.CharmSecretOwner) ([]*secrets.SecretMetadataForDrain, error)) *MockSecretServiceListCharmSecretsToDrainCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSecretServiceListCharmSecretsToDrainCall) DoAndReturn(f func(context.Context, ...service.CharmSecretOwner) ([]*secrets.SecretMetadataForDrain, error)) *MockSecretServiceListCharmSecretsToDrainCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListUserSecretsToDrain mocks base method.
func (m *MockSecretService) ListUserSecretsToDrain(ctx context.Context) ([]*secrets.SecretMetadataForDrain, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUserSecretsToDrain", ctx)
	ret0, _ := ret[0].([]*secrets.SecretMetadataForDrain)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUserSecretsToDrain indicates an expected call of ListUserSecretsToDrain.
func (mr *MockSecretServiceMockRecorder) ListUserSecretsToDrain(ctx any) *MockSecretServiceListUserSecretsToDrainCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUserSecretsToDrain", reflect.TypeOf((*MockSecretService)(nil).ListUserSecretsToDrain), ctx)
	return &MockSecretServiceListUserSecretsToDrainCall{Call: call}
}

// MockSecretServiceListUserSecretsToDrainCall wrap *gomock.Call
type MockSecretServiceListUserSecretsToDrainCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSecretServiceListUserSecretsToDrainCall) Return(arg0 []*secrets.SecretMetadataForDrain, arg1 error) *MockSecretServiceListUserSecretsToDrainCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSecretServiceListUserSecretsToDrainCall) Do(f func(context.Context) ([]*secrets.SecretMetadataForDrain, error)) *MockSecretServiceListUserSecretsToDrainCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSecretServiceListUserSecretsToDrainCall) DoAndReturn(f func(context.Context) ([]*secrets.SecretMetadataForDrain, error)) *MockSecretServiceListUserSecretsToDrainCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockSecretBackendService is a mock of SecretBackendService interface.
type MockSecretBackendService struct {
	ctrl     *gomock.Controller
	recorder *MockSecretBackendServiceMockRecorder
	isgomock struct{}
}

// MockSecretBackendServiceMockRecorder is the mock recorder for MockSecretBackendService.
type MockSecretBackendServiceMockRecorder struct {
	mock *MockSecretBackendService
}

// NewMockSecretBackendService creates a new mock instance.
func NewMockSecretBackendService(ctrl *gomock.Controller) *MockSecretBackendService {
	mock := &MockSecretBackendService{ctrl: ctrl}
	mock.recorder = &MockSecretBackendServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSecretBackendService) EXPECT() *MockSecretBackendServiceMockRecorder {
	return m.recorder
}

// GetRevisionsToDrain mocks base method.
func (m *MockSecretBackendService) GetRevisionsToDrain(ctx context.Context, modelUUID model.UUID, revs []secrets.SecretExternalRevision) ([]service0.RevisionInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRevisionsToDrain", ctx, modelUUID, revs)
	ret0, _ := ret[0].([]service0.RevisionInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRevisionsToDrain indicates an expected call of GetRevisionsToDrain.
func (mr *MockSecretBackendServiceMockRecorder) GetRevisionsToDrain(ctx, modelUUID, revs any) *MockSecretBackendServiceGetRevisionsToDrainCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRevisionsToDrain", reflect.TypeOf((*MockSecretBackendService)(nil).GetRevisionsToDrain), ctx, modelUUID, revs)
	return &MockSecretBackendServiceGetRevisionsToDrainCall{Call: call}
}

// MockSecretBackendServiceGetRevisionsToDrainCall wrap *gomock.Call
type MockSecretBackendServiceGetRevisionsToDrainCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSecretBackendServiceGetRevisionsToDrainCall) Return(arg0 []service0.RevisionInfo, arg1 error) *MockSecretBackendServiceGetRevisionsToDrainCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSecretBackendServiceGetRevisionsToDrainCall) Do(f func(context.Context, model.UUID, []secrets.SecretExternalRevision) ([]service0.RevisionInfo, error)) *MockSecretBackendServiceGetRevisionsToDrainCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSecretBackendServiceGetRevisionsToDrainCall) DoAndReturn(f func(context.Context, model.UUID, []secrets.SecretExternalRevision) ([]service0.RevisionInfo, error)) *MockSecretBackendServiceGetRevisionsToDrainCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// WatchModelSecretBackendChanged mocks base method.
func (m *MockSecretBackendService) WatchModelSecretBackendChanged(ctx context.Context, modelUUID model.UUID) (watcher.NotifyWatcher, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WatchModelSecretBackendChanged", ctx, modelUUID)
	ret0, _ := ret[0].(watcher.NotifyWatcher)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WatchModelSecretBackendChanged indicates an expected call of WatchModelSecretBackendChanged.
func (mr *MockSecretBackendServiceMockRecorder) WatchModelSecretBackendChanged(ctx, modelUUID any) *MockSecretBackendServiceWatchModelSecretBackendChangedCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WatchModelSecretBackendChanged", reflect.TypeOf((*MockSecretBackendService)(nil).WatchModelSecretBackendChanged), ctx, modelUUID)
	return &MockSecretBackendServiceWatchModelSecretBackendChangedCall{Call: call}
}

// MockSecretBackendServiceWatchModelSecretBackendChangedCall wrap *gomock.Call
type MockSecretBackendServiceWatchModelSecretBackendChangedCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSecretBackendServiceWatchModelSecretBackendChangedCall) Return(arg0 watcher.NotifyWatcher, arg1 error) *MockSecretBackendServiceWatchModelSecretBackendChangedCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSecretBackendServiceWatchModelSecretBackendChangedCall) Do(f func(context.Context, model.UUID) (watcher.NotifyWatcher, error)) *MockSecretBackendServiceWatchModelSecretBackendChangedCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSecretBackendServiceWatchModelSecretBackendChangedCall) DoAndReturn(f func(context.Context, model.UUID) (watcher.NotifyWatcher, error)) *MockSecretBackendServiceWatchModelSecretBackendChangedCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
