// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/juju/juju/core/resource (interfaces: Opener)
//
// Generated by this command:
//
//	mockgen -typed -package resources -destination resource_opener_mock_test.go github.com/juju/juju/core/resource Opener
//

// Package resources is a generated GoMock package.
package resources

import (
	context "context"
	reflect "reflect"

	resource "github.com/juju/juju/core/resource"
	gomock "go.uber.org/mock/gomock"
)

// MockOpener is a mock of Opener interface.
type MockOpener struct {
	ctrl     *gomock.Controller
	recorder *MockOpenerMockRecorder
	isgomock struct{}
}

// MockOpenerMockRecorder is the mock recorder for MockOpener.
type MockOpenerMockRecorder struct {
	mock *MockOpener
}

// NewMockOpener creates a new mock instance.
func NewMockOpener(ctrl *gomock.Controller) *MockOpener {
	mock := &MockOpener{ctrl: ctrl}
	mock.recorder = &MockOpenerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOpener) EXPECT() *MockOpenerMockRecorder {
	return m.recorder
}

// OpenResource mocks base method.
func (m *MockOpener) OpenResource(ctx context.Context, name string) (resource.Opened, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OpenResource", ctx, name)
	ret0, _ := ret[0].(resource.Opened)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OpenResource indicates an expected call of OpenResource.
func (mr *MockOpenerMockRecorder) OpenResource(ctx, name any) *MockOpenerOpenResourceCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OpenResource", reflect.TypeOf((*MockOpener)(nil).OpenResource), ctx, name)
	return &MockOpenerOpenResourceCall{Call: call}
}

// MockOpenerOpenResourceCall wrap *gomock.Call
type MockOpenerOpenResourceCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockOpenerOpenResourceCall) Return(arg0 resource.Opened, arg1 error) *MockOpenerOpenResourceCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockOpenerOpenResourceCall) Do(f func(context.Context, string) (resource.Opened, error)) *MockOpenerOpenResourceCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockOpenerOpenResourceCall) DoAndReturn(f func(context.Context, string) (resource.Opened, error)) *MockOpenerOpenResourceCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SetResourceUsed mocks base method.
func (m *MockOpener) SetResourceUsed(ctx context.Context, resName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetResourceUsed", ctx, resName)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetResourceUsed indicates an expected call of SetResourceUsed.
func (mr *MockOpenerMockRecorder) SetResourceUsed(ctx, resName any) *MockOpenerSetResourceUsedCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetResourceUsed", reflect.TypeOf((*MockOpener)(nil).SetResourceUsed), ctx, resName)
	return &MockOpenerSetResourceUsedCall{Call: call}
}

// MockOpenerSetResourceUsedCall wrap *gomock.Call
type MockOpenerSetResourceUsedCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockOpenerSetResourceUsedCall) Return(arg0 error) *MockOpenerSetResourceUsedCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockOpenerSetResourceUsedCall) Do(f func(context.Context, string) error) *MockOpenerSetResourceUsedCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockOpenerSetResourceUsedCall) DoAndReturn(f func(context.Context, string) error) *MockOpenerSetResourceUsedCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
