// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/juju/juju/core/watcher (interfaces: SecretBackendRotateWatcher)
//
// Generated by this command:
//
//	mockgen -typed -package secretbackendmanager -destination mock_watcher.go github.com/juju/juju/core/watcher SecretBackendRotateWatcher
//

// Package secretbackendmanager is a generated GoMock package.
package secretbackendmanager

import (
	reflect "reflect"

	watcher "github.com/juju/juju/core/watcher"
	gomock "go.uber.org/mock/gomock"
)

// MockSecretBackendRotateWatcher is a mock of SecretBackendRotateWatcher interface.
type MockSecretBackendRotateWatcher[T any] struct {
	ctrl     *gomock.Controller
	recorder *MockSecretBackendRotateWatcherMockRecorder[T]
	isgomock struct{}
}

// MockSecretBackendRotateWatcherMockRecorder is the mock recorder for MockSecretBackendRotateWatcher.
type MockSecretBackendRotateWatcherMockRecorder[T any] struct {
	mock *MockSecretBackendRotateWatcher[T]
}

// NewMockSecretBackendRotateWatcher creates a new mock instance.
func NewMockSecretBackendRotateWatcher[T any](ctrl *gomock.Controller) *MockSecretBackendRotateWatcher[T] {
	mock := &MockSecretBackendRotateWatcher[T]{ctrl: ctrl}
	mock.recorder = &MockSecretBackendRotateWatcherMockRecorder[T]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSecretBackendRotateWatcher[T]) EXPECT() *MockSecretBackendRotateWatcherMockRecorder[T] {
	return m.recorder
}

// Changes mocks base method.
func (m *MockSecretBackendRotateWatcher[T]) Changes() <-chan []watcher.SecretBackendRotateChange {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Changes")
	ret0, _ := ret[0].(<-chan []watcher.SecretBackendRotateChange)
	return ret0
}

// Changes indicates an expected call of Changes.
func (mr *MockSecretBackendRotateWatcherMockRecorder[T]) Changes() *MockSecretBackendRotateWatcherChangesCall[T] {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Changes", reflect.TypeOf((*MockSecretBackendRotateWatcher[T])(nil).Changes))
	return &MockSecretBackendRotateWatcherChangesCall[T]{Call: call}
}

// MockSecretBackendRotateWatcherChangesCall wrap *gomock.Call
type MockSecretBackendRotateWatcherChangesCall[T any] struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSecretBackendRotateWatcherChangesCall[T]) Return(arg0 <-chan []watcher.SecretBackendRotateChange) *MockSecretBackendRotateWatcherChangesCall[T] {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSecretBackendRotateWatcherChangesCall[T]) Do(f func() <-chan []watcher.SecretBackendRotateChange) *MockSecretBackendRotateWatcherChangesCall[T] {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSecretBackendRotateWatcherChangesCall[T]) DoAndReturn(f func() <-chan []watcher.SecretBackendRotateChange) *MockSecretBackendRotateWatcherChangesCall[T] {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Kill mocks base method.
func (m *MockSecretBackendRotateWatcher[T]) Kill() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Kill")
}

// Kill indicates an expected call of Kill.
func (mr *MockSecretBackendRotateWatcherMockRecorder[T]) Kill() *MockSecretBackendRotateWatcherKillCall[T] {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Kill", reflect.TypeOf((*MockSecretBackendRotateWatcher[T])(nil).Kill))
	return &MockSecretBackendRotateWatcherKillCall[T]{Call: call}
}

// MockSecretBackendRotateWatcherKillCall wrap *gomock.Call
type MockSecretBackendRotateWatcherKillCall[T any] struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSecretBackendRotateWatcherKillCall[T]) Return() *MockSecretBackendRotateWatcherKillCall[T] {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSecretBackendRotateWatcherKillCall[T]) Do(f func()) *MockSecretBackendRotateWatcherKillCall[T] {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSecretBackendRotateWatcherKillCall[T]) DoAndReturn(f func()) *MockSecretBackendRotateWatcherKillCall[T] {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Wait mocks base method.
func (m *MockSecretBackendRotateWatcher[T]) Wait() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Wait")
	ret0, _ := ret[0].(error)
	return ret0
}

// Wait indicates an expected call of Wait.
func (mr *MockSecretBackendRotateWatcherMockRecorder[T]) Wait() *MockSecretBackendRotateWatcherWaitCall[T] {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Wait", reflect.TypeOf((*MockSecretBackendRotateWatcher[T])(nil).Wait))
	return &MockSecretBackendRotateWatcherWaitCall[T]{Call: call}
}

// MockSecretBackendRotateWatcherWaitCall wrap *gomock.Call
type MockSecretBackendRotateWatcherWaitCall[T any] struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSecretBackendRotateWatcherWaitCall[T]) Return(arg0 error) *MockSecretBackendRotateWatcherWaitCall[T] {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSecretBackendRotateWatcherWaitCall[T]) Do(f func() error) *MockSecretBackendRotateWatcherWaitCall[T] {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSecretBackendRotateWatcherWaitCall[T]) DoAndReturn(f func() error) *MockSecretBackendRotateWatcherWaitCall[T] {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
