// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/juju/juju/cmd/containeragent/utils (interfaces: FileReaderWriter)
//
// Generated by this command:
//
//	mockgen -typed -package mocks -destination mocks/file_mock.go github.com/juju/juju/cmd/containeragent/utils FileReaderWriter
//

// Package mocks is a generated GoMock package.
package mocks

import (
	io "io"
	os "os"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockFileReaderWriter is a mock of FileReaderWriter interface.
type MockFileReaderWriter struct {
	ctrl     *gomock.Controller
	recorder *MockFileReaderWriterMockRecorder
	isgomock struct{}
}

// MockFileReaderWriterMockRecorder is the mock recorder for MockFileReaderWriter.
type MockFileReaderWriterMockRecorder struct {
	mock *MockFileReaderWriter
}

// NewMockFileReaderWriter creates a new mock instance.
func NewMockFileReaderWriter(ctrl *gomock.Controller) *MockFileReaderWriter {
	mock := &MockFileReaderWriter{ctrl: ctrl}
	mock.recorder = &MockFileReaderWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFileReaderWriter) EXPECT() *MockFileReaderWriterMockRecorder {
	return m.recorder
}

// MkdirAll mocks base method.
func (m *MockFileReaderWriter) MkdirAll(path string, perm os.FileMode) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MkdirAll", path, perm)
	ret0, _ := ret[0].(error)
	return ret0
}

// MkdirAll indicates an expected call of MkdirAll.
func (mr *MockFileReaderWriterMockRecorder) MkdirAll(path, perm any) *MockFileReaderWriterMkdirAllCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MkdirAll", reflect.TypeOf((*MockFileReaderWriter)(nil).MkdirAll), path, perm)
	return &MockFileReaderWriterMkdirAllCall{Call: call}
}

// MockFileReaderWriterMkdirAllCall wrap *gomock.Call
type MockFileReaderWriterMkdirAllCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockFileReaderWriterMkdirAllCall) Return(arg0 error) *MockFileReaderWriterMkdirAllCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockFileReaderWriterMkdirAllCall) Do(f func(string, os.FileMode) error) *MockFileReaderWriterMkdirAllCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockFileReaderWriterMkdirAllCall) DoAndReturn(f func(string, os.FileMode) error) *MockFileReaderWriterMkdirAllCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ReadFile mocks base method.
func (m *MockFileReaderWriter) ReadFile(filename string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadFile", filename)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadFile indicates an expected call of ReadFile.
func (mr *MockFileReaderWriterMockRecorder) ReadFile(filename any) *MockFileReaderWriterReadFileCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadFile", reflect.TypeOf((*MockFileReaderWriter)(nil).ReadFile), filename)
	return &MockFileReaderWriterReadFileCall{Call: call}
}

// MockFileReaderWriterReadFileCall wrap *gomock.Call
type MockFileReaderWriterReadFileCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockFileReaderWriterReadFileCall) Return(arg0 []byte, arg1 error) *MockFileReaderWriterReadFileCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockFileReaderWriterReadFileCall) Do(f func(string) ([]byte, error)) *MockFileReaderWriterReadFileCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockFileReaderWriterReadFileCall) DoAndReturn(f func(string) ([]byte, error)) *MockFileReaderWriterReadFileCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Reader mocks base method.
func (m *MockFileReaderWriter) Reader(filename string) (io.ReadCloser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reader", filename)
	ret0, _ := ret[0].(io.ReadCloser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Reader indicates an expected call of Reader.
func (mr *MockFileReaderWriterMockRecorder) Reader(filename any) *MockFileReaderWriterReaderCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reader", reflect.TypeOf((*MockFileReaderWriter)(nil).Reader), filename)
	return &MockFileReaderWriterReaderCall{Call: call}
}

// MockFileReaderWriterReaderCall wrap *gomock.Call
type MockFileReaderWriterReaderCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockFileReaderWriterReaderCall) Return(arg0 io.ReadCloser, arg1 error) *MockFileReaderWriterReaderCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockFileReaderWriterReaderCall) Do(f func(string) (io.ReadCloser, error)) *MockFileReaderWriterReaderCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockFileReaderWriterReaderCall) DoAndReturn(f func(string) (io.ReadCloser, error)) *MockFileReaderWriterReaderCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// RemoveAll mocks base method.
func (m *MockFileReaderWriter) RemoveAll(path string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveAll", path)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveAll indicates an expected call of RemoveAll.
func (mr *MockFileReaderWriterMockRecorder) RemoveAll(path any) *MockFileReaderWriterRemoveAllCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveAll", reflect.TypeOf((*MockFileReaderWriter)(nil).RemoveAll), path)
	return &MockFileReaderWriterRemoveAllCall{Call: call}
}

// MockFileReaderWriterRemoveAllCall wrap *gomock.Call
type MockFileReaderWriterRemoveAllCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockFileReaderWriterRemoveAllCall) Return(arg0 error) *MockFileReaderWriterRemoveAllCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockFileReaderWriterRemoveAllCall) Do(f func(string) error) *MockFileReaderWriterRemoveAllCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockFileReaderWriterRemoveAllCall) DoAndReturn(f func(string) error) *MockFileReaderWriterRemoveAllCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Stat mocks base method.
func (m *MockFileReaderWriter) Stat(filename string) (os.FileInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stat", filename)
	ret0, _ := ret[0].(os.FileInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Stat indicates an expected call of Stat.
func (mr *MockFileReaderWriterMockRecorder) Stat(filename any) *MockFileReaderWriterStatCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stat", reflect.TypeOf((*MockFileReaderWriter)(nil).Stat), filename)
	return &MockFileReaderWriterStatCall{Call: call}
}

// MockFileReaderWriterStatCall wrap *gomock.Call
type MockFileReaderWriterStatCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockFileReaderWriterStatCall) Return(arg0 os.FileInfo, arg1 error) *MockFileReaderWriterStatCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockFileReaderWriterStatCall) Do(f func(string) (os.FileInfo, error)) *MockFileReaderWriterStatCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockFileReaderWriterStatCall) DoAndReturn(f func(string) (os.FileInfo, error)) *MockFileReaderWriterStatCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Symlink mocks base method.
func (m *MockFileReaderWriter) Symlink(oldname, newname string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Symlink", oldname, newname)
	ret0, _ := ret[0].(error)
	return ret0
}

// Symlink indicates an expected call of Symlink.
func (mr *MockFileReaderWriterMockRecorder) Symlink(oldname, newname any) *MockFileReaderWriterSymlinkCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Symlink", reflect.TypeOf((*MockFileReaderWriter)(nil).Symlink), oldname, newname)
	return &MockFileReaderWriterSymlinkCall{Call: call}
}

// MockFileReaderWriterSymlinkCall wrap *gomock.Call
type MockFileReaderWriterSymlinkCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockFileReaderWriterSymlinkCall) Return(arg0 error) *MockFileReaderWriterSymlinkCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockFileReaderWriterSymlinkCall) Do(f func(string, string) error) *MockFileReaderWriterSymlinkCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockFileReaderWriterSymlinkCall) DoAndReturn(f func(string, string) error) *MockFileReaderWriterSymlinkCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// WriteFile mocks base method.
func (m *MockFileReaderWriter) WriteFile(filename string, data []byte, perm os.FileMode) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteFile", filename, data, perm)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteFile indicates an expected call of WriteFile.
func (mr *MockFileReaderWriterMockRecorder) WriteFile(filename, data, perm any) *MockFileReaderWriterWriteFileCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteFile", reflect.TypeOf((*MockFileReaderWriter)(nil).WriteFile), filename, data, perm)
	return &MockFileReaderWriterWriteFileCall{Call: call}
}

// MockFileReaderWriterWriteFileCall wrap *gomock.Call
type MockFileReaderWriterWriteFileCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockFileReaderWriterWriteFileCall) Return(arg0 error) *MockFileReaderWriterWriteFileCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockFileReaderWriterWriteFileCall) Do(f func(string, []byte, os.FileMode) error) *MockFileReaderWriterWriteFileCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockFileReaderWriterWriteFileCall) DoAndReturn(f func(string, []byte, os.FileMode) error) *MockFileReaderWriterWriteFileCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Writer mocks base method.
func (m *MockFileReaderWriter) Writer(filename string, perm os.FileMode) (io.WriteCloser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Writer", filename, perm)
	ret0, _ := ret[0].(io.WriteCloser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Writer indicates an expected call of Writer.
func (mr *MockFileReaderWriterMockRecorder) Writer(filename, perm any) *MockFileReaderWriterWriterCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Writer", reflect.TypeOf((*MockFileReaderWriter)(nil).Writer), filename, perm)
	return &MockFileReaderWriterWriterCall{Call: call}
}

// MockFileReaderWriterWriterCall wrap *gomock.Call
type MockFileReaderWriterWriterCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockFileReaderWriterWriterCall) Return(arg0 io.WriteCloser, arg1 error) *MockFileReaderWriterWriterCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockFileReaderWriterWriterCall) Do(f func(string, os.FileMode) (io.WriteCloser, error)) *MockFileReaderWriterWriterCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockFileReaderWriterWriterCall) DoAndReturn(f func(string, os.FileMode) (io.WriteCloser, error)) *MockFileReaderWriterWriterCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
