// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/juju/juju/internal/provider/kubernetes/resources (interfaces: Resource,Applier)
//
// Generated by this command:
//
//	mockgen -typed -package mocks -destination mocks/resources_mock.go github.com/juju/juju/internal/provider/kubernetes/resources Resource,Applier
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	status "github.com/juju/juju/core/status"
	resources "github.com/juju/juju/internal/provider/kubernetes/resources"
	gomock "go.uber.org/mock/gomock"
	v1 "k8s.io/api/core/v1"
	v10 "k8s.io/apimachinery/pkg/apis/meta/v1"
	kubernetes "k8s.io/client-go/kubernetes"
)

// MockResource is a mock of Resource interface.
type MockResource struct {
	ctrl     *gomock.Controller
	recorder *MockResourceMockRecorder
	isgomock struct{}
}

// MockResourceMockRecorder is the mock recorder for MockResource.
type MockResourceMockRecorder struct {
	mock *MockResource
}

// NewMockResource creates a new mock instance.
func NewMockResource(ctrl *gomock.Controller) *MockResource {
	mock := &MockResource{ctrl: ctrl}
	mock.recorder = &MockResourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockResource) EXPECT() *MockResourceMockRecorder {
	return m.recorder
}

// Apply mocks base method.
func (m *MockResource) Apply(ctx context.Context, client kubernetes.Interface) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Apply", ctx, client)
	ret0, _ := ret[0].(error)
	return ret0
}

// Apply indicates an expected call of Apply.
func (mr *MockResourceMockRecorder) Apply(ctx, client any) *MockResourceApplyCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Apply", reflect.TypeOf((*MockResource)(nil).Apply), ctx, client)
	return &MockResourceApplyCall{Call: call}
}

// MockResourceApplyCall wrap *gomock.Call
type MockResourceApplyCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockResourceApplyCall) Return(arg0 error) *MockResourceApplyCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockResourceApplyCall) Do(f func(context.Context, kubernetes.Interface) error) *MockResourceApplyCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockResourceApplyCall) DoAndReturn(f func(context.Context, kubernetes.Interface) error) *MockResourceApplyCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Clone mocks base method.
func (m *MockResource) Clone() resources.Resource {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Clone")
	ret0, _ := ret[0].(resources.Resource)
	return ret0
}

// Clone indicates an expected call of Clone.
func (mr *MockResourceMockRecorder) Clone() *MockResourceCloneCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Clone", reflect.TypeOf((*MockResource)(nil).Clone))
	return &MockResourceCloneCall{Call: call}
}

// MockResourceCloneCall wrap *gomock.Call
type MockResourceCloneCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockResourceCloneCall) Return(arg0 resources.Resource) *MockResourceCloneCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockResourceCloneCall) Do(f func() resources.Resource) *MockResourceCloneCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockResourceCloneCall) DoAndReturn(f func() resources.Resource) *MockResourceCloneCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ComputeStatus mocks base method.
func (m *MockResource) ComputeStatus(ctx context.Context, client kubernetes.Interface, now time.Time) (string, status.Status, time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ComputeStatus", ctx, client, now)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(status.Status)
	ret2, _ := ret[2].(time.Time)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// ComputeStatus indicates an expected call of ComputeStatus.
func (mr *MockResourceMockRecorder) ComputeStatus(ctx, client, now any) *MockResourceComputeStatusCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ComputeStatus", reflect.TypeOf((*MockResource)(nil).ComputeStatus), ctx, client, now)
	return &MockResourceComputeStatusCall{Call: call}
}

// MockResourceComputeStatusCall wrap *gomock.Call
type MockResourceComputeStatusCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockResourceComputeStatusCall) Return(arg0 string, arg1 status.Status, arg2 time.Time, arg3 error) *MockResourceComputeStatusCall {
	c.Call = c.Call.Return(arg0, arg1, arg2, arg3)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockResourceComputeStatusCall) Do(f func(context.Context, kubernetes.Interface, time.Time) (string, status.Status, time.Time, error)) *MockResourceComputeStatusCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockResourceComputeStatusCall) DoAndReturn(f func(context.Context, kubernetes.Interface, time.Time) (string, status.Status, time.Time, error)) *MockResourceComputeStatusCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Delete mocks base method.
func (m *MockResource) Delete(ctx context.Context, client kubernetes.Interface) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, client)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockResourceMockRecorder) Delete(ctx, client any) *MockResourceDeleteCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockResource)(nil).Delete), ctx, client)
	return &MockResourceDeleteCall{Call: call}
}

// MockResourceDeleteCall wrap *gomock.Call
type MockResourceDeleteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockResourceDeleteCall) Return(arg0 error) *MockResourceDeleteCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockResourceDeleteCall) Do(f func(context.Context, kubernetes.Interface) error) *MockResourceDeleteCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockResourceDeleteCall) DoAndReturn(f func(context.Context, kubernetes.Interface) error) *MockResourceDeleteCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Events mocks base method.
func (m *MockResource) Events(ctx context.Context, client kubernetes.Interface) ([]v1.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Events", ctx, client)
	ret0, _ := ret[0].([]v1.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Events indicates an expected call of Events.
func (mr *MockResourceMockRecorder) Events(ctx, client any) *MockResourceEventsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Events", reflect.TypeOf((*MockResource)(nil).Events), ctx, client)
	return &MockResourceEventsCall{Call: call}
}

// MockResourceEventsCall wrap *gomock.Call
type MockResourceEventsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockResourceEventsCall) Return(arg0 []v1.Event, arg1 error) *MockResourceEventsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockResourceEventsCall) Do(f func(context.Context, kubernetes.Interface) ([]v1.Event, error)) *MockResourceEventsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockResourceEventsCall) DoAndReturn(f func(context.Context, kubernetes.Interface) ([]v1.Event, error)) *MockResourceEventsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Get mocks base method.
func (m *MockResource) Get(ctx context.Context, client kubernetes.Interface) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, client)
	ret0, _ := ret[0].(error)
	return ret0
}

// Get indicates an expected call of Get.
func (mr *MockResourceMockRecorder) Get(ctx, client any) *MockResourceGetCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockResource)(nil).Get), ctx, client)
	return &MockResourceGetCall{Call: call}
}

// MockResourceGetCall wrap *gomock.Call
type MockResourceGetCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockResourceGetCall) Return(arg0 error) *MockResourceGetCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockResourceGetCall) Do(f func(context.Context, kubernetes.Interface) error) *MockResourceGetCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockResourceGetCall) DoAndReturn(f func(context.Context, kubernetes.Interface) error) *MockResourceGetCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetObjectMeta mocks base method.
func (m *MockResource) GetObjectMeta() v10.Object {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetObjectMeta")
	ret0, _ := ret[0].(v10.Object)
	return ret0
}

// GetObjectMeta indicates an expected call of GetObjectMeta.
func (mr *MockResourceMockRecorder) GetObjectMeta() *MockResourceGetObjectMetaCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetObjectMeta", reflect.TypeOf((*MockResource)(nil).GetObjectMeta))
	return &MockResourceGetObjectMetaCall{Call: call}
}

// MockResourceGetObjectMetaCall wrap *gomock.Call
type MockResourceGetObjectMetaCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockResourceGetObjectMetaCall) Return(arg0 v10.Object) *MockResourceGetObjectMetaCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockResourceGetObjectMetaCall) Do(f func() v10.Object) *MockResourceGetObjectMetaCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockResourceGetObjectMetaCall) DoAndReturn(f func() v10.Object) *MockResourceGetObjectMetaCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ID mocks base method.
func (m *MockResource) ID() resources.ID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ID")
	ret0, _ := ret[0].(resources.ID)
	return ret0
}

// ID indicates an expected call of ID.
func (mr *MockResourceMockRecorder) ID() *MockResourceIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ID", reflect.TypeOf((*MockResource)(nil).ID))
	return &MockResourceIDCall{Call: call}
}

// MockResourceIDCall wrap *gomock.Call
type MockResourceIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockResourceIDCall) Return(arg0 resources.ID) *MockResourceIDCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockResourceIDCall) Do(f func() resources.ID) *MockResourceIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockResourceIDCall) DoAndReturn(f func() resources.ID) *MockResourceIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// String mocks base method.
func (m *MockResource) String() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "String")
	ret0, _ := ret[0].(string)
	return ret0
}

// String indicates an expected call of String.
func (mr *MockResourceMockRecorder) String() *MockResourceStringCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "String", reflect.TypeOf((*MockResource)(nil).String))
	return &MockResourceStringCall{Call: call}
}

// MockResourceStringCall wrap *gomock.Call
type MockResourceStringCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockResourceStringCall) Return(arg0 string) *MockResourceStringCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockResourceStringCall) Do(f func() string) *MockResourceStringCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockResourceStringCall) DoAndReturn(f func() string) *MockResourceStringCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockApplier is a mock of Applier interface.
type MockApplier struct {
	ctrl     *gomock.Controller
	recorder *MockApplierMockRecorder
	isgomock struct{}
}

// MockApplierMockRecorder is the mock recorder for MockApplier.
type MockApplierMockRecorder struct {
	mock *MockApplier
}

// NewMockApplier creates a new mock instance.
func NewMockApplier(ctrl *gomock.Controller) *MockApplier {
	mock := &MockApplier{ctrl: ctrl}
	mock.recorder = &MockApplierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockApplier) EXPECT() *MockApplierMockRecorder {
	return m.recorder
}

// Apply mocks base method.
func (m *MockApplier) Apply(arg0 ...resources.Resource) {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range arg0 {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Apply", varargs...)
}

// Apply indicates an expected call of Apply.
func (mr *MockApplierMockRecorder) Apply(arg0 ...any) *MockApplierApplyCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Apply", reflect.TypeOf((*MockApplier)(nil).Apply), arg0...)
	return &MockApplierApplyCall{Call: call}
}

// MockApplierApplyCall wrap *gomock.Call
type MockApplierApplyCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockApplierApplyCall) Return() *MockApplierApplyCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockApplierApplyCall) Do(f func(...resources.Resource)) *MockApplierApplyCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockApplierApplyCall) DoAndReturn(f func(...resources.Resource)) *MockApplierApplyCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ApplySet mocks base method.
func (m *MockApplier) ApplySet(current, desired []resources.Resource) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ApplySet", current, desired)
}

// ApplySet indicates an expected call of ApplySet.
func (mr *MockApplierMockRecorder) ApplySet(current, desired any) *MockApplierApplySetCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplySet", reflect.TypeOf((*MockApplier)(nil).ApplySet), current, desired)
	return &MockApplierApplySetCall{Call: call}
}

// MockApplierApplySetCall wrap *gomock.Call
type MockApplierApplySetCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockApplierApplySetCall) Return() *MockApplierApplySetCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockApplierApplySetCall) Do(f func([]resources.Resource, []resources.Resource)) *MockApplierApplySetCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockApplierApplySetCall) DoAndReturn(f func([]resources.Resource, []resources.Resource)) *MockApplierApplySetCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Delete mocks base method.
func (m *MockApplier) Delete(arg0 ...resources.Resource) {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range arg0 {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Delete", varargs...)
}

// Delete indicates an expected call of Delete.
func (mr *MockApplierMockRecorder) Delete(arg0 ...any) *MockApplierDeleteCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockApplier)(nil).Delete), arg0...)
	return &MockApplierDeleteCall{Call: call}
}

// MockApplierDeleteCall wrap *gomock.Call
type MockApplierDeleteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockApplierDeleteCall) Return() *MockApplierDeleteCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockApplierDeleteCall) Do(f func(...resources.Resource)) *MockApplierDeleteCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockApplierDeleteCall) DoAndReturn(f func(...resources.Resource)) *MockApplierDeleteCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Run mocks base method.
func (m *MockApplier) Run(ctx context.Context, client kubernetes.Interface, noRollback bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", ctx, client, noRollback)
	ret0, _ := ret[0].(error)
	return ret0
}

// Run indicates an expected call of Run.
func (mr *MockApplierMockRecorder) Run(ctx, client, noRollback any) *MockApplierRunCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockApplier)(nil).Run), ctx, client, noRollback)
	return &MockApplierRunCall{Call: call}
}

// MockApplierRunCall wrap *gomock.Call
type MockApplierRunCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockApplierRunCall) Return(arg0 error) *MockApplierRunCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockApplierRunCall) Do(f func(context.Context, kubernetes.Interface, bool) error) *MockApplierRunCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockApplierRunCall) DoAndReturn(f func(context.Context, kubernetes.Interface, bool) error) *MockApplierRunCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
