// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/juju/juju/apiserver/facades/client/resources (interfaces: ApplicationService,ResourceService,NewCharmRepository)
//
// Generated by this command:
//
//	mockgen -typed -package resources -destination service_mock_test.go github.com/juju/juju/apiserver/facades/client/resources ApplicationService,ResourceService,NewCharmRepository
//

// Package resources is a generated GoMock package.
package resources

import (
	context "context"
	reflect "reflect"

	application "github.com/juju/juju/core/application"
	charm "github.com/juju/juju/core/charm"
	resource "github.com/juju/juju/core/resource"
	resource0 "github.com/juju/juju/domain/resource"
	resource1 "github.com/juju/juju/internal/charm/resource"
	gomock "go.uber.org/mock/gomock"
)

// MockApplicationService is a mock of ApplicationService interface.
type MockApplicationService struct {
	ctrl     *gomock.Controller
	recorder *MockApplicationServiceMockRecorder
	isgomock struct{}
}

// MockApplicationServiceMockRecorder is the mock recorder for MockApplicationService.
type MockApplicationServiceMockRecorder struct {
	mock *MockApplicationService
}

// NewMockApplicationService creates a new mock instance.
func NewMockApplicationService(ctrl *gomock.Controller) *MockApplicationService {
	mock := &MockApplicationService{ctrl: ctrl}
	mock.recorder = &MockApplicationServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockApplicationService) EXPECT() *MockApplicationServiceMockRecorder {
	return m.recorder
}

// GetApplicationIDByName mocks base method.
func (m *MockApplicationService) GetApplicationIDByName(ctx context.Context, name string) (application.ID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetApplicationIDByName", ctx, name)
	ret0, _ := ret[0].(application.ID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetApplicationIDByName indicates an expected call of GetApplicationIDByName.
func (mr *MockApplicationServiceMockRecorder) GetApplicationIDByName(ctx, name any) *MockApplicationServiceGetApplicationIDByNameCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetApplicationIDByName", reflect.TypeOf((*MockApplicationService)(nil).GetApplicationIDByName), ctx, name)
	return &MockApplicationServiceGetApplicationIDByNameCall{Call: call}
}

// MockApplicationServiceGetApplicationIDByNameCall wrap *gomock.Call
type MockApplicationServiceGetApplicationIDByNameCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockApplicationServiceGetApplicationIDByNameCall) Return(arg0 application.ID, arg1 error) *MockApplicationServiceGetApplicationIDByNameCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockApplicationServiceGetApplicationIDByNameCall) Do(f func(context.Context, string) (application.ID, error)) *MockApplicationServiceGetApplicationIDByNameCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockApplicationServiceGetApplicationIDByNameCall) DoAndReturn(f func(context.Context, string) (application.ID, error)) *MockApplicationServiceGetApplicationIDByNameCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockResourceService is a mock of ResourceService interface.
type MockResourceService struct {
	ctrl     *gomock.Controller
	recorder *MockResourceServiceMockRecorder
	isgomock struct{}
}

// MockResourceServiceMockRecorder is the mock recorder for MockResourceService.
type MockResourceServiceMockRecorder struct {
	mock *MockResourceService
}

// NewMockResourceService creates a new mock instance.
func NewMockResourceService(ctrl *gomock.Controller) *MockResourceService {
	mock := &MockResourceService{ctrl: ctrl}
	mock.recorder = &MockResourceServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockResourceService) EXPECT() *MockResourceServiceMockRecorder {
	return m.recorder
}

// AddResourcesBeforeApplication mocks base method.
func (m *MockResourceService) AddResourcesBeforeApplication(ctx context.Context, arg resource0.AddResourcesBeforeApplicationArgs) ([]resource.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddResourcesBeforeApplication", ctx, arg)
	ret0, _ := ret[0].([]resource.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddResourcesBeforeApplication indicates an expected call of AddResourcesBeforeApplication.
func (mr *MockResourceServiceMockRecorder) AddResourcesBeforeApplication(ctx, arg any) *MockResourceServiceAddResourcesBeforeApplicationCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddResourcesBeforeApplication", reflect.TypeOf((*MockResourceService)(nil).AddResourcesBeforeApplication), ctx, arg)
	return &MockResourceServiceAddResourcesBeforeApplicationCall{Call: call}
}

// MockResourceServiceAddResourcesBeforeApplicationCall wrap *gomock.Call
type MockResourceServiceAddResourcesBeforeApplicationCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockResourceServiceAddResourcesBeforeApplicationCall) Return(arg0 []resource.UUID, arg1 error) *MockResourceServiceAddResourcesBeforeApplicationCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockResourceServiceAddResourcesBeforeApplicationCall) Do(f func(context.Context, resource0.AddResourcesBeforeApplicationArgs) ([]resource.UUID, error)) *MockResourceServiceAddResourcesBeforeApplicationCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockResourceServiceAddResourcesBeforeApplicationCall) DoAndReturn(f func(context.Context, resource0.AddResourcesBeforeApplicationArgs) ([]resource.UUID, error)) *MockResourceServiceAddResourcesBeforeApplicationCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetApplicationResourceID mocks base method.
func (m *MockResourceService) GetApplicationResourceID(ctx context.Context, args resource0.GetApplicationResourceIDArgs) (resource.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetApplicationResourceID", ctx, args)
	ret0, _ := ret[0].(resource.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetApplicationResourceID indicates an expected call of GetApplicationResourceID.
func (mr *MockResourceServiceMockRecorder) GetApplicationResourceID(ctx, args any) *MockResourceServiceGetApplicationResourceIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetApplicationResourceID", reflect.TypeOf((*MockResourceService)(nil).GetApplicationResourceID), ctx, args)
	return &MockResourceServiceGetApplicationResourceIDCall{Call: call}
}

// MockResourceServiceGetApplicationResourceIDCall wrap *gomock.Call
type MockResourceServiceGetApplicationResourceIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockResourceServiceGetApplicationResourceIDCall) Return(arg0 resource.UUID, arg1 error) *MockResourceServiceGetApplicationResourceIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockResourceServiceGetApplicationResourceIDCall) Do(f func(context.Context, resource0.GetApplicationResourceIDArgs) (resource.UUID, error)) *MockResourceServiceGetApplicationResourceIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockResourceServiceGetApplicationResourceIDCall) DoAndReturn(f func(context.Context, resource0.GetApplicationResourceIDArgs) (resource.UUID, error)) *MockResourceServiceGetApplicationResourceIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListResources mocks base method.
func (m *MockResourceService) ListResources(ctx context.Context, applicationID application.ID) (resource.ApplicationResources, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListResources", ctx, applicationID)
	ret0, _ := ret[0].(resource.ApplicationResources)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListResources indicates an expected call of ListResources.
func (mr *MockResourceServiceMockRecorder) ListResources(ctx, applicationID any) *MockResourceServiceListResourcesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListResources", reflect.TypeOf((*MockResourceService)(nil).ListResources), ctx, applicationID)
	return &MockResourceServiceListResourcesCall{Call: call}
}

// MockResourceServiceListResourcesCall wrap *gomock.Call
type MockResourceServiceListResourcesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockResourceServiceListResourcesCall) Return(arg0 resource.ApplicationResources, arg1 error) *MockResourceServiceListResourcesCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockResourceServiceListResourcesCall) Do(f func(context.Context, application.ID) (resource.ApplicationResources, error)) *MockResourceServiceListResourcesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockResourceServiceListResourcesCall) DoAndReturn(f func(context.Context, application.ID) (resource.ApplicationResources, error)) *MockResourceServiceListResourcesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateResourceRevision mocks base method.
func (m *MockResourceService) UpdateResourceRevision(ctx context.Context, args resource0.UpdateResourceRevisionArgs) (resource.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateResourceRevision", ctx, args)
	ret0, _ := ret[0].(resource.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateResourceRevision indicates an expected call of UpdateResourceRevision.
func (mr *MockResourceServiceMockRecorder) UpdateResourceRevision(ctx, args any) *MockResourceServiceUpdateResourceRevisionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateResourceRevision", reflect.TypeOf((*MockResourceService)(nil).UpdateResourceRevision), ctx, args)
	return &MockResourceServiceUpdateResourceRevisionCall{Call: call}
}

// MockResourceServiceUpdateResourceRevisionCall wrap *gomock.Call
type MockResourceServiceUpdateResourceRevisionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockResourceServiceUpdateResourceRevisionCall) Return(arg0 resource.UUID, arg1 error) *MockResourceServiceUpdateResourceRevisionCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockResourceServiceUpdateResourceRevisionCall) Do(f func(context.Context, resource0.UpdateResourceRevisionArgs) (resource.UUID, error)) *MockResourceServiceUpdateResourceRevisionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockResourceServiceUpdateResourceRevisionCall) DoAndReturn(f func(context.Context, resource0.UpdateResourceRevisionArgs) (resource.UUID, error)) *MockResourceServiceUpdateResourceRevisionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateUploadResource mocks base method.
func (m *MockResourceService) UpdateUploadResource(ctx context.Context, resourceToUpdate resource.UUID) (resource.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUploadResource", ctx, resourceToUpdate)
	ret0, _ := ret[0].(resource.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUploadResource indicates an expected call of UpdateUploadResource.
func (mr *MockResourceServiceMockRecorder) UpdateUploadResource(ctx, resourceToUpdate any) *MockResourceServiceUpdateUploadResourceCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUploadResource", reflect.TypeOf((*MockResourceService)(nil).UpdateUploadResource), ctx, resourceToUpdate)
	return &MockResourceServiceUpdateUploadResourceCall{Call: call}
}

// MockResourceServiceUpdateUploadResourceCall wrap *gomock.Call
type MockResourceServiceUpdateUploadResourceCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockResourceServiceUpdateUploadResourceCall) Return(arg0 resource.UUID, arg1 error) *MockResourceServiceUpdateUploadResourceCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockResourceServiceUpdateUploadResourceCall) Do(f func(context.Context, resource.UUID) (resource.UUID, error)) *MockResourceServiceUpdateUploadResourceCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockResourceServiceUpdateUploadResourceCall) DoAndReturn(f func(context.Context, resource.UUID) (resource.UUID, error)) *MockResourceServiceUpdateUploadResourceCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockNewCharmRepository is a mock of NewCharmRepository interface.
type MockNewCharmRepository struct {
	ctrl     *gomock.Controller
	recorder *MockNewCharmRepositoryMockRecorder
	isgomock struct{}
}

// MockNewCharmRepositoryMockRecorder is the mock recorder for MockNewCharmRepository.
type MockNewCharmRepositoryMockRecorder struct {
	mock *MockNewCharmRepository
}

// NewMockNewCharmRepository creates a new mock instance.
func NewMockNewCharmRepository(ctrl *gomock.Controller) *MockNewCharmRepository {
	mock := &MockNewCharmRepository{ctrl: ctrl}
	mock.recorder = &MockNewCharmRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNewCharmRepository) EXPECT() *MockNewCharmRepositoryMockRecorder {
	return m.recorder
}

// ResolveResources mocks base method.
func (m *MockNewCharmRepository) ResolveResources(ctx context.Context, resources []resource1.Resource, id charm.CharmID) ([]resource1.Resource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveResources", ctx, resources, id)
	ret0, _ := ret[0].([]resource1.Resource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveResources indicates an expected call of ResolveResources.
func (mr *MockNewCharmRepositoryMockRecorder) ResolveResources(ctx, resources, id any) *MockNewCharmRepositoryResolveResourcesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveResources", reflect.TypeOf((*MockNewCharmRepository)(nil).ResolveResources), ctx, resources, id)
	return &MockNewCharmRepositoryResolveResourcesCall{Call: call}
}

// MockNewCharmRepositoryResolveResourcesCall wrap *gomock.Call
type MockNewCharmRepositoryResolveResourcesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockNewCharmRepositoryResolveResourcesCall) Return(arg0 []resource1.Resource, arg1 error) *MockNewCharmRepositoryResolveResourcesCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockNewCharmRepositoryResolveResourcesCall) Do(f func(context.Context, []resource1.Resource, charm.CharmID) ([]resource1.Resource, error)) *MockNewCharmRepositoryResolveResourcesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockNewCharmRepositoryResolveResourcesCall) DoAndReturn(f func(context.Context, []resource1.Resource, charm.CharmID) ([]resource1.Resource, error)) *MockNewCharmRepositoryResolveResourcesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
