// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/juju/juju/core/objectstore (interfaces: ObjectStoreMetadata,Session)
//
// Generated by this command:
//
//	mockgen -typed -package objectstore -destination objectstore_mock_test.go github.com/juju/juju/core/objectstore ObjectStoreMetadata,Session
//

// Package objectstore is a generated GoMock package.
package objectstore

import (
	context "context"
	io "io"
	reflect "reflect"

	objectstore "github.com/juju/juju/core/objectstore"
	watcher "github.com/juju/juju/core/watcher"
	gomock "go.uber.org/mock/gomock"
)

// MockObjectStoreMetadata is a mock of ObjectStoreMetadata interface.
type MockObjectStoreMetadata struct {
	ctrl     *gomock.Controller
	recorder *MockObjectStoreMetadataMockRecorder
	isgomock struct{}
}

// MockObjectStoreMetadataMockRecorder is the mock recorder for MockObjectStoreMetadata.
type MockObjectStoreMetadataMockRecorder struct {
	mock *MockObjectStoreMetadata
}

// NewMockObjectStoreMetadata creates a new mock instance.
func NewMockObjectStoreMetadata(ctrl *gomock.Controller) *MockObjectStoreMetadata {
	mock := &MockObjectStoreMetadata{ctrl: ctrl}
	mock.recorder = &MockObjectStoreMetadataMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockObjectStoreMetadata) EXPECT() *MockObjectStoreMetadataMockRecorder {
	return m.recorder
}

// GetMetadata mocks base method.
func (m *MockObjectStoreMetadata) GetMetadata(ctx context.Context, path string) (objectstore.Metadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMetadata", ctx, path)
	ret0, _ := ret[0].(objectstore.Metadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMetadata indicates an expected call of GetMetadata.
func (mr *MockObjectStoreMetadataMockRecorder) GetMetadata(ctx, path any) *MockObjectStoreMetadataGetMetadataCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMetadata", reflect.TypeOf((*MockObjectStoreMetadata)(nil).GetMetadata), ctx, path)
	return &MockObjectStoreMetadataGetMetadataCall{Call: call}
}

// MockObjectStoreMetadataGetMetadataCall wrap *gomock.Call
type MockObjectStoreMetadataGetMetadataCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockObjectStoreMetadataGetMetadataCall) Return(arg0 objectstore.Metadata, arg1 error) *MockObjectStoreMetadataGetMetadataCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockObjectStoreMetadataGetMetadataCall) Do(f func(context.Context, string) (objectstore.Metadata, error)) *MockObjectStoreMetadataGetMetadataCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockObjectStoreMetadataGetMetadataCall) DoAndReturn(f func(context.Context, string) (objectstore.Metadata, error)) *MockObjectStoreMetadataGetMetadataCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetMetadataBySHA256 mocks base method.
func (m *MockObjectStoreMetadata) GetMetadataBySHA256(ctx context.Context, sha256 string) (objectstore.Metadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMetadataBySHA256", ctx, sha256)
	ret0, _ := ret[0].(objectstore.Metadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMetadataBySHA256 indicates an expected call of GetMetadataBySHA256.
func (mr *MockObjectStoreMetadataMockRecorder) GetMetadataBySHA256(ctx, sha256 any) *MockObjectStoreMetadataGetMetadataBySHA256Call {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMetadataBySHA256", reflect.TypeOf((*MockObjectStoreMetadata)(nil).GetMetadataBySHA256), ctx, sha256)
	return &MockObjectStoreMetadataGetMetadataBySHA256Call{Call: call}
}

// MockObjectStoreMetadataGetMetadataBySHA256Call wrap *gomock.Call
type MockObjectStoreMetadataGetMetadataBySHA256Call struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockObjectStoreMetadataGetMetadataBySHA256Call) Return(arg0 objectstore.Metadata, arg1 error) *MockObjectStoreMetadataGetMetadataBySHA256Call {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockObjectStoreMetadataGetMetadataBySHA256Call) Do(f func(context.Context, string) (objectstore.Metadata, error)) *MockObjectStoreMetadataGetMetadataBySHA256Call {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockObjectStoreMetadataGetMetadataBySHA256Call) DoAndReturn(f func(context.Context, string) (objectstore.Metadata, error)) *MockObjectStoreMetadataGetMetadataBySHA256Call {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetMetadataBySHA256Prefix mocks base method.
func (m *MockObjectStoreMetadata) GetMetadataBySHA256Prefix(ctx context.Context, sha256Prefix string) (objectstore.Metadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMetadataBySHA256Prefix", ctx, sha256Prefix)
	ret0, _ := ret[0].(objectstore.Metadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMetadataBySHA256Prefix indicates an expected call of GetMetadataBySHA256Prefix.
func (mr *MockObjectStoreMetadataMockRecorder) GetMetadataBySHA256Prefix(ctx, sha256Prefix any) *MockObjectStoreMetadataGetMetadataBySHA256PrefixCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMetadataBySHA256Prefix", reflect.TypeOf((*MockObjectStoreMetadata)(nil).GetMetadataBySHA256Prefix), ctx, sha256Prefix)
	return &MockObjectStoreMetadataGetMetadataBySHA256PrefixCall{Call: call}
}

// MockObjectStoreMetadataGetMetadataBySHA256PrefixCall wrap *gomock.Call
type MockObjectStoreMetadataGetMetadataBySHA256PrefixCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockObjectStoreMetadataGetMetadataBySHA256PrefixCall) Return(arg0 objectstore.Metadata, arg1 error) *MockObjectStoreMetadataGetMetadataBySHA256PrefixCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockObjectStoreMetadataGetMetadataBySHA256PrefixCall) Do(f func(context.Context, string) (objectstore.Metadata, error)) *MockObjectStoreMetadataGetMetadataBySHA256PrefixCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockObjectStoreMetadataGetMetadataBySHA256PrefixCall) DoAndReturn(f func(context.Context, string) (objectstore.Metadata, error)) *MockObjectStoreMetadataGetMetadataBySHA256PrefixCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListMetadata mocks base method.
func (m *MockObjectStoreMetadata) ListMetadata(ctx context.Context) ([]objectstore.Metadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMetadata", ctx)
	ret0, _ := ret[0].([]objectstore.Metadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMetadata indicates an expected call of ListMetadata.
func (mr *MockObjectStoreMetadataMockRecorder) ListMetadata(ctx any) *MockObjectStoreMetadataListMetadataCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMetadata", reflect.TypeOf((*MockObjectStoreMetadata)(nil).ListMetadata), ctx)
	return &MockObjectStoreMetadataListMetadataCall{Call: call}
}

// MockObjectStoreMetadataListMetadataCall wrap *gomock.Call
type MockObjectStoreMetadataListMetadataCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockObjectStoreMetadataListMetadataCall) Return(arg0 []objectstore.Metadata, arg1 error) *MockObjectStoreMetadataListMetadataCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockObjectStoreMetadataListMetadataCall) Do(f func(context.Context) ([]objectstore.Metadata, error)) *MockObjectStoreMetadataListMetadataCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockObjectStoreMetadataListMetadataCall) DoAndReturn(f func(context.Context) ([]objectstore.Metadata, error)) *MockObjectStoreMetadataListMetadataCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// PutMetadata mocks base method.
func (m *MockObjectStoreMetadata) PutMetadata(ctx context.Context, metadata objectstore.Metadata) (objectstore.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutMetadata", ctx, metadata)
	ret0, _ := ret[0].(objectstore.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PutMetadata indicates an expected call of PutMetadata.
func (mr *MockObjectStoreMetadataMockRecorder) PutMetadata(ctx, metadata any) *MockObjectStoreMetadataPutMetadataCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutMetadata", reflect.TypeOf((*MockObjectStoreMetadata)(nil).PutMetadata), ctx, metadata)
	return &MockObjectStoreMetadataPutMetadataCall{Call: call}
}

// MockObjectStoreMetadataPutMetadataCall wrap *gomock.Call
type MockObjectStoreMetadataPutMetadataCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockObjectStoreMetadataPutMetadataCall) Return(arg0 objectstore.UUID, arg1 error) *MockObjectStoreMetadataPutMetadataCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockObjectStoreMetadataPutMetadataCall) Do(f func(context.Context, objectstore.Metadata) (objectstore.UUID, error)) *MockObjectStoreMetadataPutMetadataCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockObjectStoreMetadataPutMetadataCall) DoAndReturn(f func(context.Context, objectstore.Metadata) (objectstore.UUID, error)) *MockObjectStoreMetadataPutMetadataCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// RemoveMetadata mocks base method.
func (m *MockObjectStoreMetadata) RemoveMetadata(ctx context.Context, path string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveMetadata", ctx, path)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveMetadata indicates an expected call of RemoveMetadata.
func (mr *MockObjectStoreMetadataMockRecorder) RemoveMetadata(ctx, path any) *MockObjectStoreMetadataRemoveMetadataCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveMetadata", reflect.TypeOf((*MockObjectStoreMetadata)(nil).RemoveMetadata), ctx, path)
	return &MockObjectStoreMetadataRemoveMetadataCall{Call: call}
}

// MockObjectStoreMetadataRemoveMetadataCall wrap *gomock.Call
type MockObjectStoreMetadataRemoveMetadataCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockObjectStoreMetadataRemoveMetadataCall) Return(arg0 error) *MockObjectStoreMetadataRemoveMetadataCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockObjectStoreMetadataRemoveMetadataCall) Do(f func(context.Context, string) error) *MockObjectStoreMetadataRemoveMetadataCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockObjectStoreMetadataRemoveMetadataCall) DoAndReturn(f func(context.Context, string) error) *MockObjectStoreMetadataRemoveMetadataCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Watch mocks base method.
func (m *MockObjectStoreMetadata) Watch() (watcher.StringsWatcher, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Watch")
	ret0, _ := ret[0].(watcher.StringsWatcher)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Watch indicates an expected call of Watch.
func (mr *MockObjectStoreMetadataMockRecorder) Watch() *MockObjectStoreMetadataWatchCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Watch", reflect.TypeOf((*MockObjectStoreMetadata)(nil).Watch))
	return &MockObjectStoreMetadataWatchCall{Call: call}
}

// MockObjectStoreMetadataWatchCall wrap *gomock.Call
type MockObjectStoreMetadataWatchCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockObjectStoreMetadataWatchCall) Return(arg0 watcher.StringsWatcher, arg1 error) *MockObjectStoreMetadataWatchCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockObjectStoreMetadataWatchCall) Do(f func() (watcher.StringsWatcher, error)) *MockObjectStoreMetadataWatchCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockObjectStoreMetadataWatchCall) DoAndReturn(f func() (watcher.StringsWatcher, error)) *MockObjectStoreMetadataWatchCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockSession is a mock of Session interface.
type MockSession struct {
	ctrl     *gomock.Controller
	recorder *MockSessionMockRecorder
	isgomock struct{}
}

// MockSessionMockRecorder is the mock recorder for MockSession.
type MockSessionMockRecorder struct {
	mock *MockSession
}

// NewMockSession creates a new mock instance.
func NewMockSession(ctrl *gomock.Controller) *MockSession {
	mock := &MockSession{ctrl: ctrl}
	mock.recorder = &MockSessionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSession) EXPECT() *MockSessionMockRecorder {
	return m.recorder
}

// CreateBucket mocks base method.
func (m *MockSession) CreateBucket(ctx context.Context, bucketName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBucket", ctx, bucketName)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateBucket indicates an expected call of CreateBucket.
func (mr *MockSessionMockRecorder) CreateBucket(ctx, bucketName any) *MockSessionCreateBucketCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBucket", reflect.TypeOf((*MockSession)(nil).CreateBucket), ctx, bucketName)
	return &MockSessionCreateBucketCall{Call: call}
}

// MockSessionCreateBucketCall wrap *gomock.Call
type MockSessionCreateBucketCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSessionCreateBucketCall) Return(arg0 error) *MockSessionCreateBucketCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSessionCreateBucketCall) Do(f func(context.Context, string) error) *MockSessionCreateBucketCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSessionCreateBucketCall) DoAndReturn(f func(context.Context, string) error) *MockSessionCreateBucketCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteObject mocks base method.
func (m *MockSession) DeleteObject(ctx context.Context, bucketName, objectName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteObject", ctx, bucketName, objectName)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteObject indicates an expected call of DeleteObject.
func (mr *MockSessionMockRecorder) DeleteObject(ctx, bucketName, objectName any) *MockSessionDeleteObjectCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteObject", reflect.TypeOf((*MockSession)(nil).DeleteObject), ctx, bucketName, objectName)
	return &MockSessionDeleteObjectCall{Call: call}
}

// MockSessionDeleteObjectCall wrap *gomock.Call
type MockSessionDeleteObjectCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSessionDeleteObjectCall) Return(arg0 error) *MockSessionDeleteObjectCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSessionDeleteObjectCall) Do(f func(context.Context, string, string) error) *MockSessionDeleteObjectCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSessionDeleteObjectCall) DoAndReturn(f func(context.Context, string, string) error) *MockSessionDeleteObjectCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetObject mocks base method.
func (m *MockSession) GetObject(ctx context.Context, bucketName, objectName string) (io.ReadCloser, int64, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetObject", ctx, bucketName, objectName)
	ret0, _ := ret[0].(io.ReadCloser)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(string)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// GetObject indicates an expected call of GetObject.
func (mr *MockSessionMockRecorder) GetObject(ctx, bucketName, objectName any) *MockSessionGetObjectCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetObject", reflect.TypeOf((*MockSession)(nil).GetObject), ctx, bucketName, objectName)
	return &MockSessionGetObjectCall{Call: call}
}

// MockSessionGetObjectCall wrap *gomock.Call
type MockSessionGetObjectCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSessionGetObjectCall) Return(arg0 io.ReadCloser, arg1 int64, arg2 string, arg3 error) *MockSessionGetObjectCall {
	c.Call = c.Call.Return(arg0, arg1, arg2, arg3)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSessionGetObjectCall) Do(f func(context.Context, string, string) (io.ReadCloser, int64, string, error)) *MockSessionGetObjectCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSessionGetObjectCall) DoAndReturn(f func(context.Context, string, string) (io.ReadCloser, int64, string, error)) *MockSessionGetObjectCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListObjects mocks base method.
func (m *MockSession) ListObjects(ctx context.Context, bucketName string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListObjects", ctx, bucketName)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListObjects indicates an expected call of ListObjects.
func (mr *MockSessionMockRecorder) ListObjects(ctx, bucketName any) *MockSessionListObjectsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListObjects", reflect.TypeOf((*MockSession)(nil).ListObjects), ctx, bucketName)
	return &MockSessionListObjectsCall{Call: call}
}

// MockSessionListObjectsCall wrap *gomock.Call
type MockSessionListObjectsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSessionListObjectsCall) Return(arg0 []string, arg1 error) *MockSessionListObjectsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSessionListObjectsCall) Do(f func(context.Context, string) ([]string, error)) *MockSessionListObjectsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSessionListObjectsCall) DoAndReturn(f func(context.Context, string) ([]string, error)) *MockSessionListObjectsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ObjectExists mocks base method.
func (m *MockSession) ObjectExists(ctx context.Context, bucketName, objectName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ObjectExists", ctx, bucketName, objectName)
	ret0, _ := ret[0].(error)
	return ret0
}

// ObjectExists indicates an expected call of ObjectExists.
func (mr *MockSessionMockRecorder) ObjectExists(ctx, bucketName, objectName any) *MockSessionObjectExistsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ObjectExists", reflect.TypeOf((*MockSession)(nil).ObjectExists), ctx, bucketName, objectName)
	return &MockSessionObjectExistsCall{Call: call}
}

// MockSessionObjectExistsCall wrap *gomock.Call
type MockSessionObjectExistsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSessionObjectExistsCall) Return(arg0 error) *MockSessionObjectExistsCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSessionObjectExistsCall) Do(f func(context.Context, string, string) error) *MockSessionObjectExistsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSessionObjectExistsCall) DoAndReturn(f func(context.Context, string, string) error) *MockSessionObjectExistsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// PutObject mocks base method.
func (m *MockSession) PutObject(ctx context.Context, bucketName, objectName string, body io.Reader, hash string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutObject", ctx, bucketName, objectName, body, hash)
	ret0, _ := ret[0].(error)
	return ret0
}

// PutObject indicates an expected call of PutObject.
func (mr *MockSessionMockRecorder) PutObject(ctx, bucketName, objectName, body, hash any) *MockSessionPutObjectCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutObject", reflect.TypeOf((*MockSession)(nil).PutObject), ctx, bucketName, objectName, body, hash)
	return &MockSessionPutObjectCall{Call: call}
}

// MockSessionPutObjectCall wrap *gomock.Call
type MockSessionPutObjectCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSessionPutObjectCall) Return(arg0 error) *MockSessionPutObjectCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSessionPutObjectCall) Do(f func(context.Context, string, string, io.Reader, string) error) *MockSessionPutObjectCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSessionPutObjectCall) DoAndReturn(f func(context.Context, string, string, io.Reader, string) error) *MockSessionPutObjectCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
