name: "Client Tests"
on:
  push:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - '**.go'
      - 'go.mod'
      - '.github/workflows/client-tests.yml'
  workflow_dispatch:

permissions:
  contents: read

jobs:

  test-client-ubuntu:
    name: "Client Tests"
    runs-on: ${{ matrix.os }}
    if: github.event.pull_request.draft == false
    strategy:
      fail-fast: false
      matrix:
        # windows tests is disabled because we require a certain version of
        # mongo (that's actually going away now though), and choclately was
        # failing to install it correctly.
        # os: [ubuntu-latest, macOS-latest, windows-latest]
        os: [macOS-latest]

    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version-file: 'go.mod'
        cache: true

    - name: "Install Mongo Dependencies: ubuntu-latest"
      if: (matrix.os == 'ubuntu-latest')
      run: |
        make install-mongo-dependencies

    - name: "Remove Mongo Dependencies: windows-latest"
      if: (matrix.os == 'windows-latest')
      uses: crazy-max/ghaction-chocolatey@b59ffdb6594d2e2c36d9e1174e15ac799dd0a8f1 # v1
      with:
        args: uninstall mongodb mongodb.install -y --all-versions

    - name: "Install Mongo Dependencies: windows-latest"
      if: (matrix.os == 'windows-latest')
      uses: crazy-max/ghaction-chocolatey@b59ffdb6594d2e2c36d9e1174e15ac799dd0a8f1 # v1
      with:
        args: install mongodb.install --version=4.4.25 --allow-downgrade

    # GitHub runners already have preinstalled version of mongodb, but
    # we specifically need 4.4.x, otherwise our tests will not pass
    - name: "Install Mongo Dependencies: macOS-latest"
      if: (matrix.os == 'macOS-latest')
      run: |
        curl -o mongodb-4.4.25.tgz https://fastdl.mongodb.org/osx/mongodb-macos-x86_64-4.4.25.tgz
        tar xzvf mongodb-4.4.25.tgz
        sudo rm -rf /usr/local/mongodb
        sudo mkdir -p /usr/local/mongodb
        sudo mv mongodb-macos-x86_64-4.4.25/bin/* /usr/local/mongodb
        sudo mkdir -p /usr/local/bin
        sudo rm /usr/local/bin/mongod
        sudo ln -s /usr/local/mongodb/mongod /usr/local/bin/mongod
      shell: bash

    - name: "Test client: macOS-latest"
      if: (matrix.os == 'macOS-latest')
      run: |
        # We increase the number of file descriptors that processes can have 
        # open so mongo doesn't fail. Client tests still rely on mongo and as
        # such we have a high request count for FD's
        ulimit -n 64000
        go test ./cmd/juju/...
        go test ./cmd/plugins/...
      shell: bash

    - name: "Test client: ubuntu-latest"
      if: (matrix.os == 'ubuntu-latest')
      run: |
        # Jenkins can perform the full jujud testing.
        go test -race -v ./cmd/juju/... -coverprofile=coverage.txt -covermode=atomic -timeout=15m
        go test -race -v ./cmd/plugins/...
      shell: bash
