name: "Migrate"
on:
  push:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - '**.go'
      - 'go.mod'
      - 'snap/**'
      - '.github/workflows/migrate.yml'
      - 'scripts/dqlite/**'
      - 'Makefile'
      - 'make_functions.sh'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  migrate:
    name: 3.1-to-4.x
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    strategy:
      fail-fast: false
      matrix:
        # TODO: add microk8s tests
        cloud: ["lxd"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Enable Snap parallel-instances
        run: |
          sudo snap set system experimental.parallel-instances=true

      - name: Setup LXD
        if: matrix.cloud == 'lxd'
        uses: canonical/setup-lxd@4e959f8e0d9c5feb27d44c5e4d9a330a782edee0

      - name: Install Juju 3.1
        run: |
          sudo snap install juju_31 --channel 3.1/stable

      - name: Bootstrap a 3.1 controller and model
        run: |
          juju_31 bootstrap lxd test31
          juju_31 add-model test-migrate
          juju_31 deploy ubuntu
          
          # TODO: use juju-restore
          # TODO: add users/permissions/models and test that those migrate over

      - name: Set up Go
        uses: actions/setup-go@v4

      - name: Set up Go env
        run: |
          echo "GOPATH=$(go env GOPATH)" >> $GITHUB_ENV
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Upgrade client to 4.x
        run: |
          make go-install &>/dev/null

      - name: Bootstrap 4.x controller
        run: |
          juju bootstrap lxd test4x
          juju switch controller
          juju wait-for application controller || juju status -m controller

        # TODO: create backup and juju restore

      - name: Migrate default model to 4.x controller
        run: |
          juju_31 switch test31
          
          # Ensure application is fully deployed
          juju_31 wait-for application ubuntu
          
          # Wait a few secs for the machine status to update
          # so that migration prechecks pass.
          sleep 10
          
          juju_31 migrate test-migrate test4x

      - name: Check the migration was successful
        run: |
          set -x
          juju switch test4x
          
          # Wait for 'test-migrate' model to come through
          attempt=0
          while true; do
            RES=$(juju models | grep 'test-migrate' || true)
            if [[ -n $RES ]]; then
              break
            fi
            sleep 5
            attempt=$((attempt+1))
            if [ "$attempt" -eq 10 ]; then
              echo "Migration timed out"
              exit 1
            fi
          done
          
          juju switch test-migrate
          juju wait-for application ubuntu
          
          juju deploy ubuntu yet-another-ubuntu
          juju wait-for application yet-another-ubuntu
