name: "Smoke"
on:
  push:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - '**.go'
      - 'go.mod'
      - 'testcharms/**'
      - 'tests/main.sh'
      - 'tests/includes/**'
      - 'tests/suites/smoke/**'
      - '.github/workflows/smoke.yml'
  workflow_dispatch:

permissions:
  contents: read

jobs:

  smoke:
    name: Smoke
    runs-on: [self-hosted, linux, arm64, aws, xlarge]
    if: github.event.pull_request.draft == false
    strategy:
      fail-fast: false
      matrix:
        cloud: ["localhost", "microk8s"]
    steps:

    - name: Install Dependencies
      shell: bash
      run: |
        set -euxo pipefail
        echo "/snap/bin" >> $GITHUB_PATH
        sudo DEBIAN_FRONTEND=noninteractive apt install -y expect

    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup LXD
      if: matrix.cloud == 'localhost'
      uses: canonical/setup-lxd@90d76101915da56a42a562ba766b1a77019242fd

    - name: Setup MicroK8s
      if: matrix.cloud == 'microk8s'
      uses: hpidcock/microk8s-actions@48dcc39f92380c5ff8721f031607e9f9aeef9cab
      with:
        channel: "1.25/stable"
        addons: '["dns", "hostpath-storage", "rbac"]'

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version-file: 'go.mod'
        cache: true

    - name: setup env
      shell: bash
      run: |
        echo "GOPATH=$(go env GOPATH)" >> $GITHUB_ENV
        echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

    - name: Install local Juju
      shell: bash
      run: |
        make go-install

    - name: Update microk8s operator image
      if: matrix.cloud == 'microk8s'
      run: |
        # TODO: use temporary Docker account (set DOCKER_USERNAME env var)
        sg microk8s 'make microk8s-operator-update'

    - name: Smoke test (LXD)
      if: matrix.cloud == 'localhost'
      shell: bash
      run: |
        cd tests
        export MODEL_ARCH=$(go env GOARCH)
        ./main.sh -v -s 'test_build' smoke

    - name: Smoke test (MicroK8s)
      if: matrix.cloud == 'microk8s'
      shell: bash
      run: |
        cd tests
        export MODEL_ARCH=$(go env GOARCH)
        sg microk8s './main.sh -c microk8s -s test_build -v smoke'
